language: php

services:
  - docker

install: skip

scripts:
  - docker build -t w1491413492/yzmcms:6.0.1 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push w1491413492/yzmcms:6.0.1